language: python
python:
  - "2.6"
  - "2.7"
install:
  - ln -s profiles/production.cfg buildout.cfg
  - pip install --upgrade setuptools
  - python bootstrap.py -c ./.travis.cfg
script:
  - bin/buildout
